// Generated by the Currai skill. Native HTTP only; no Currai SDK.
type CurraiEventKind =
  | "agent"
  | "model"
  | "tool"
  | "mcp_tool"
  | "retriever"
  | "guardrail"
  | "evaluator"
  | "event";

type CurraiEvent = {
  eventId?: string;
  sessionId: string;
  sessionAccepted: boolean;
  parentId?: string | null;
  kind: CurraiEventKind;
  name: string;
  args?: unknown;
  result?: unknown;
  success?: boolean;
  latency?: number;
  timestamp?: number;
  metadata?: Record<string, unknown>;
};

const sensitiveKey =
  /authorization|cookie|password|passwd|secret|api[-_]?key|access[-_]?token|refresh[-_]?token|bearer/i;

function redact(value: unknown, seen = new WeakSet<object>()): unknown {
  if (value == null || typeof value !== "object") return value;
  if (seen.has(value)) return "[Circular]";
  seen.add(value);
  if (Array.isArray(value)) return value.map((item) => redact(item, seen));
  return Object.fromEntries(
    Object.entries(value as Record<string, unknown>).map(([key, item]) => [
      key,
      sensitiveKey.test(key) ? "[REDACTED]" : redact(item, seen),
    ]),
  );
}

function encode(value: unknown): string {
  try {
    return JSON.stringify(redact(value));
  } catch {
    return JSON.stringify({ value: String(value) });
  }
}

async function send(path: string, body: unknown): Promise<boolean> {
  const baseUrl = process.env.CURRAI_BASE_URL;
  const publicKey = process.env.CURRAI_PUBLIC_KEY;
  const secretKey = process.env.CURRAI_SECRET_KEY;
  if (!baseUrl || !publicKey || !secretKey) return false;
  try {
    const response = await fetch(`${baseUrl.replace(/\/$/, "")}${path}`, {
      method: "POST",
      headers: {
        "content-type": "application/json",
        authorization:
          "Basic " + Buffer.from(publicKey + ":" + secretKey).toString("base64"),
      },
      body: JSON.stringify(redact(body)),
      signal: AbortSignal.timeout(2_000),
    });
    return response.ok;
  } catch {
    return false;
  }
}

export async function captureCurraiSession(input: {
  sessionId: string;
  userId: string;
  properties?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
  timestamp?: number;
}): Promise<boolean> {
  const accepted = await send("/api/v1/capture-session", {
    session_id: input.sessionId,
    user_data: { user_id: input.userId, properties: input.properties ?? {} },
    metadata: input.metadata ?? {},
    timestamp: input.timestamp,
    client_config: "currai-skill-native-http",
  });
  return accepted;
}

export async function captureCurraiEvent(
  input: CurraiEvent,
): Promise<boolean> {
  if (!input.sessionAccepted) return false;
  return send("/api/v1/capture-event", {
    event_id: input.eventId ?? crypto.randomUUID(),
    session_id: input.sessionId,
    parent_id: input.parentId ?? null,
    kind: input.kind,
    primitive_name: input.name,
    args: encode(input.args ?? {}),
    result: encode(input.result ?? {}),
    success: input.success ?? true,
    latency: input.latency,
    timestamp: input.timestamp,
    metadata: redact(input.metadata ?? {}),
  });
}
